server:
  port: 8080

spring:
  application:
    name: gateway
  zipkin:
    base-url: "http://localhost:9411"
  sleuth:
    sampler:
      probability: 0.5

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: providera
          uri: http://PROVIDERA
          predicates:
              #拦截的路由，当在地址栏输入该地址时会被转发到http://PROVIDERA-SERVICE/**
            - Path=/providera/**
          filters:
            - StripPrefix=1
        - id: providerb
          uri: http://PROVIDERB
          predicates:
              #拦截的路由，当在地址栏输入该地址时会被转发到http://PROVIDERB-SERVICE/**
            - Path=/providerb/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
